CREATE TABLE IF NOT EXISTS payment_transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  checkout_request_id VARCHAR(64) NULL,
  merchant_request_id VARCHAR(64) NULL,
  mpesa_receipt VARCHAR(64) NULL,
  phone VARCHAR(32) NULL,
  amount DECIMAL(12, 2) NULL,
  account_reference VARCHAR(191) NULL,
  status ENUM('PENDING', 'SUCCESS', 'FAILED') NOT NULL DEFAULT 'PENDING',
  result_code INT NULL,
  result_desc VARCHAR(255) NULL,
  transaction_date VARCHAR(32) NULL,
  channel VARCHAR(32) NULL,
  raw_payload JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_checkout_request_id (checkout_request_id),
  KEY idx_mpesa_receipt (mpesa_receipt),
  KEY idx_phone (phone),
  KEY idx_status (status),
  KEY idx_created_at (created_at),
  KEY idx_account_reference (account_reference)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
