CREATE TABLE IF NOT EXISTS api_call_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  service ENUM('tisp', 'zoho', 'mpesa', 'other') NOT NULL,
  operation VARCHAR(100) NOT NULL,
  method VARCHAR(10) NOT NULL DEFAULT 'POST',
  endpoint VARCHAR(500) NOT NULL,
  status ENUM('success', 'failure') NOT NULL,
  http_status INT NULL,
  request_payload JSON NOT NULL,
  response_payload JSON NULL,
  error_message TEXT NULL,
  customer_id INT UNSIGNED NULL,
  customer_number VARCHAR(50) NULL,
  reference_id VARCHAR(100) NULL,
  retryable TINYINT(1) NOT NULL DEFAULT 1,
  retry_count INT UNSIGNED NOT NULL DEFAULT 0,
  parent_log_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_api_logs_service_status (service, status),
  KEY idx_api_logs_created (created_at),
  KEY idx_api_logs_customer (customer_id),
  KEY idx_api_logs_operation (operation),
  CONSTRAINT fk_api_logs_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
